### ISSUE TITLE
Error creating device: org.springframework.security.access.AccessDeniedException: Access is denied

### ISSUE THREAD

**Issue by tkdrob** [jebbett/Plex-Communicator#1]
@jebbett I'm getting this error when trying to create child devices. 

Also, is it possible to port this to hubitat?

**Comment by jebbett** [comment]
I assume you don't have the device handler installed, but difficult to tell from the error and just about to board a plane.. Hubitat code is here: https://community.hubitat.com/t/plex-webhooks/2106/16

**Comment by tkdrob** [comment]
Thanks. I tried getting it working last night just before bed so I overlooked it

**Comment by tkdrob** [comment]
Ok. I've moved to the hubitat app and driver you gave me. Child device was created but does not change status when I use plex. I've added the webhook to my server. The app indicates the state change in the logs, but the child device does not

**Comment by tkdrob** [comment]
So I have an LG smart tv with the plex app. Unlike, other devices, there is no connection uri listed for it on https://plex.tv/devices.xml. That must explain the error. Any ideas? Perhaps an option in the device driver to include the local ip and port would fix this, assuming the lg tv has any ports open for plex

**Comment by jebbett** [comment]
It uses the client identifier I think from memory, so should be unique to the player, my old app used to use IP but there were a lot of instances where it wouldn't work.. if it finds the player then it should work..

**Comment by jebbett** [comment]
If you find this line: 
def playerID = plexJSON.Player.uuid

And put this below it:
Log.debug playerID

Then you'll see what is being returned in the debug log

**Comment by tkdrob** [comment]
Thanks. I had to change the device network id to match the client identifier (player id) in the logs. It turns out that my lg tv shows as a chrome player but uses a different identifier than what shows up on https://plex.tv/devices.xml. Other than plex player control, everything else works now

**Comment by jebbett** [comment]
Ok very strange, if you set the device playing then try adding a new device then the device should show up as another addable device.. it gets devices from now playing too.. as devices that use a secondary user account don't show in the devices.xml

**Comment by jzee923** [comment]
Sorry to comment on a closed issue, but I'm also seeing the same error on SmartThings.
I have created both the SmartApp and the Device Handler (from your repo). 

EDIT:
turns out this error may be an issue with SmartThings Classic app. I tried it on the new app and it worked fine.
If it's not too much trouble, maybe you can add that as a note somewhere?
