### ISSUE TITLE
Not Working When Plex Server Only Accepts Secure Connections

### ISSUE THREAD

**Issue by tkdrob** [jebbett/Plex-Communicator#4]
Is it possible to rewrite this app to use https as an option? Thanks

**Comment by jebbett** [comment]
Are you using webhooks? Or the exe? If the exe then changing the two bits in the code from http: to https: may fix it but can't guarantee anything.. or just update in the config file to add the s. Let me know if it works, and I'll update GitHub, if it doesn't then the feature won't be added unless someone sends me a pull request..

**Comment by tkdrob** [comment]
That did not work. I'm using webhooks. What I did do is temporarily allow insecure connections for the initial connection to my plex server. I then set it back to secure only and it still worked. Since its only one way communication from the server to the hub app via webhooks, everything works now.
